<?php
declare(strict_types=1);
namespace Modright\Tests;
use Modright\Database;use PDO;use PHPUnit\Framework\TestCase;
final class MySqlMigrationTest extends TestCase
{
    private function connection():PDO
    { $dsn=(string)getenv('COGWORK_TEST_MYSQL_DSN');if($dsn===''||!in_array('mysql',PDO::getAvailableDrivers(),true))self::markTestSkipped('MariaDB test service is unavailable.');$db=new PDO($dsn,(string)getenv('COGWORK_TEST_MYSQL_USER'),(string)getenv('COGWORK_TEST_MYSQL_PASSWORD'),[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);$db->exec('SET FOREIGN_KEY_CHECKS=0');foreach($db->query('SHOW TABLES')->fetchAll(PDO::FETCH_COLUMN)as$table)$db->exec('DROP TABLE `'.str_replace('`','``',(string)$table).'`');$db->exec('SET FOREIGN_KEY_CHECKS=1');return$db;}
    public function testFreshMariaDbMigrationIsIdempotent():void
    { $db=$this->connection();Database::migrate($db);$before=(int)$db->query('SELECT COUNT(*) FROM schema_migrations')->fetchColumn();Database::migrate($db);$stmt=$db->prepare('SELECT COUNT(*) FROM schema_migrations WHERE migration_id=?');$stmt->execute([Database::LATEST_MIGRATION]);self::assertSame(1,(int)$stmt->fetchColumn());self::assertSame($before,(int)$db->query('SELECT COUNT(*) FROM schema_migrations')->fetchColumn());self::assertSame(1,(int)$db->query("SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='users' AND column_name='email'")->fetchColumn());self::assertSame(1,(int)$db->query("SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='announcements' AND column_name='archived_at'")->fetchColumn());self::assertSame(1,(int)$db->query("SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='announcements' AND column_name='activated_at'")->fetchColumn());self::assertSame(1,(int)$db->query("SELECT COUNT(*) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='announcements' AND column_name='expired_at'")->fetchColumn());}
    public function testLegacyAdministratorAndPackSurviveUpgrade():void
    { $db=$this->connection();$db->exec("CREATE TABLE admins (id VARCHAR(36) PRIMARY KEY, username VARCHAR(100) NOT NULL UNIQUE, password_hash VARCHAR(255) NOT NULL, created_at VARCHAR(30) NOT NULL)");$db->exec("CREATE TABLE packs (id VARCHAR(36) PRIMARY KEY, name VARCHAR(200) NOT NULL, slug VARCHAR(200) NOT NULL UNIQUE, version_id VARCHAR(100) NOT NULL, summary TEXT NOT NULL, game_version VARCHAR(100) NOT NULL, loader VARCHAR(30) NOT NULL, loader_version VARCHAR(100) NOT NULL, index_json TEXT NOT NULL, created_at VARCHAR(30) NOT NULL, updated_at VARCHAR(30) NOT NULL)");$hash=password_hash('legacy-password',PASSWORD_DEFAULT);$stmt=$db->prepare('INSERT INTO admins VALUES (?,?,?,?)');$stmt->execute(['admin-id','legacy',$hash,'2025-01-01T00:00:00+00:00']);$db->prepare('INSERT INTO packs VALUES (?,?,?,?,?,?,?,?,?,?,?)')->execute(['pack-id','Legacy','legacy','1','','1.20.1','fabric','0.15','{"files":[]}','2025-01-01T00:00:00+00:00','2025-01-01T00:00:00+00:00']);Database::migrate($db);self::assertSame($hash,$db->query("SELECT password_hash FROM users WHERE id='admin-id'")->fetchColumn());self::assertSame('admin-id',$db->query("SELECT user_id FROM pack_owners WHERE pack_id='pack-id'")->fetchColumn());self::assertSame('Legacy',$db->query("SELECT name FROM packs WHERE id='pack-id'")->fetchColumn());}
}
