<?php

declare(strict_types=1);

namespace Modright\Tests;

use Modright\ConfigurationService;
use Modright\Database;
use Modright\HealthService;
use Modright\RetentionService;
use Modright\SystemSettings;
use PDO;
use PHPUnit\Framework\TestCase;

final class OperationsFoundationTest extends TestCase
{
    private function database(): PDO
    { $db=new PDO('sqlite::memory:');$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$db->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE,PDO::FETCH_ASSOC);Database::migrate($db);return$db; }

    public function testHealthReportIsRedactedAndStructured(): void
    { if(!in_array('sqlite',PDO::getAvailableDrivers(),true))self::markTestSkipped();$db=$this->database();$report=(new HealthService($db,new SystemSettings($db)))->report(['HTTPS'=>'on']);self::assertContains($report['status'],['healthy','degraded','misconfigured']);self::assertNotEmpty($report['checks']);foreach($report['checks']as$check){self::assertArrayHasKey('recommendation',$check);self::assertNotSame('',trim((string)$check['recommendation']));}self::assertArrayHasKey('version',$report);self::assertStringNotContainsString('password',json_encode($report)); }

    public function testHealthSeparatesCanonicalHttpsFromEffectiveTrustedRequest():void
    { if(!in_array('sqlite',PDO::getAvailableDrivers(),true))self::markTestSkipped();$db=$this->database();$settings=new SystemSettings($db);$settings->setGroup('security',['canonical_url'=>'https://packs.example.test','trusted_proxies'=>['10.0.0.0/24']]);$service=new HealthService($db,$settings);$untrusted=[];foreach($service->report(['REMOTE_ADDR'=>'203.0.113.4','HTTP_X_FORWARDED_PROTO'=>'https'])['checks']as$check)$untrusted[$check['id']]=$check;self::assertSame('degraded',$untrusted['https']['status']);self::assertSame('misconfigured',$untrusted['trusted_proxy']['status']);self::assertSame('disabled',$untrusted['security_features']['status']);$trusted=[];foreach($service->report(['REMOTE_ADDR'=>'10.0.0.4','HTTP_X_FORWARDED_PROTO'=>'https'])['checks']as$check)$trusted[$check['id']]=$check;self::assertSame('healthy',$trusted['https']['status']);self::assertSame('healthy',$trusted['secure_cookie']['status']);self::assertSame('healthy',$trusted['security_features']['status']);}

    public function testHealthAndUpgradePreflightTreatPendingMigrationsAsBlocker():void
    { if(!in_array('sqlite',PDO::getAvailableDrivers(),true))self::markTestSkipped();$db=$this->database();$db->exec('DELETE FROM schema_migrations');$db->prepare('INSERT INTO schema_migrations (migration_id,applied_at) VALUES (?,?)')->execute(['older-migration',Database::now()]);$settings=new SystemSettings($db);$report=(new HealthService($db,$settings))->report([]);$migration=array_values(array_filter($report['checks'],fn(array$check):bool=>$check['id']==='migrations'))[0];self::assertSame('misconfigured',$migration['status']);$upgrade=(new \Modright\UpgradeReadinessService($db,$settings))->report();self::assertStringContainsString('migrations:',implode(' ',$upgrade['blockers']));}

    public function testRetentionDeletesOnlyEligibleBoundedRecords():void
    { if(!in_array('sqlite',PDO::getAvailableDrivers(),true))self::markTestSkipped();$db=$this->database();$settings=new SystemSettings($db);$old=gmdate('c',time()-400*86400);$db->prepare('INSERT INTO security_events (id,user_id,event_type,severity,context,created_at) VALUES (?,?,?,?,?,?)')->execute(['old',null,'test','info','{}',$old]);$db->prepare('INSERT INTO security_events (id,user_id,event_type,severity,context,created_at) VALUES (?,?,?,?,?,?)')->execute(['new',null,'test','info','{}',Database::now()]);$counts=(new \Modright\RetentionService($db,$settings))->cleanup(1);self::assertSame(1,$counts['security_events']);self::assertSame(1,(int)$db->query('SELECT COUNT(*) FROM security_events')->fetchColumn()); }

    public function testArchivedAnnouncementsAreNotActive():void
    { if(!in_array('sqlite',PDO::getAvailableDrivers(),true))self::markTestSkipped();$db=$this->database();$users=new \Modright\UserService($db);$id=$users->create('person','Person','long-enough-password','user','en_US','person@example.com');$user=$users->find($id);$service=new \Modright\AnnouncementService($db);$announcement=$service->save(['severity'=>'info','audience'=>'everyone','title_en'=>'Hello','message_en'=>'World']);self::assertCount(1,$service->activeFor($user));$service->archive($announcement);self::assertCount(0,$service->activeFor($user));}

    public function testRetentionPreservesMinimumRecentPackagesPerPack():void
    { if(!in_array('sqlite',PDO::getAvailableDrivers(),true))self::markTestSkipped();$db=$this->database();$settings=new SystemSettings($db);$settings->setGroup('retention',['packages_keep'=>1]);$pack=(new \Modright\PackRepository($db))->create(['formatVersion'=>1,'game'=>'minecraft','versionId'=>'1','name'=>'Retained','summary'=>'','files'=>[],'dependencies'=>['minecraft'=>'1.21.1','fabric-loader'=>'0.16']]);foreach([1,2]as$n)$db->prepare('INSERT INTO packages (id,pack_id,version_id,path,size,sha256,created_at) VALUES (?,?,?,?,?,?,?)')->execute(['package-'.$n,$pack,(string)$n,'/not/a/real/file',10,str_repeat((string)$n,64),gmdate('c',time()+$n)]);$service=new \Modright\RetentionService($db,$settings);self::assertSame(1,$service->estimate()['packages']);self::assertSame(1,$service->cleanup()['packages']);self::assertSame('2',$db->query('SELECT version_id FROM packages')->fetchColumn());}

    public function testConfigurationImportValidatesDependenciesAndKeepsRollbackSnapshot():void
    { if(!in_array('sqlite',PDO::getAvailableDrivers(),true))self::markTestSkipped();$db=$this->database();$settings=new SystemSettings($db);$settings->setGroup('security',['canonical_url'=>'https://packs.example.test']);$service=new \Modright\ConfigurationService($settings);$document=$service->export();$document['configuration']['features']['two_factor']=true;self::assertGreaterThan(0,$service->import($document));self::assertIsArray($settings->get('system.configuration_import_backup'));$bad=$service->export();$bad['configuration']['updates']['channel']='nightly';$this->expectException(\InvalidArgumentException::class);$service->preview($bad);}

    public function testConfigurationRoundTripOnlyChangesKnownNonSecrets(): void
    { if(!in_array('sqlite',PDO::getAvailableDrivers(),true))self::markTestSkipped();$db=$this->database();$settings=new SystemSettings($db);$service=new ConfigurationService($settings);$document=$service->export();$document['configuration']['features']['modrinth']=false;$document['configuration']['features']['unknown']=true;self::assertArrayHasKey('features',$service->preview($document));self::assertSame(1,$service->import($document));self::assertFalse($settings->feature('modrinth'));self::assertArrayNotHasKey('unknown',$settings->group('features'));$rollback=$settings->get('system.configuration_import_backup');self::assertIsArray($rollback);self::assertGreaterThan(0,$service->import($rollback,'replace'));self::assertTrue($settings->feature('modrinth')); }

    public function testConfigurationCarriesNonPersonalNotificationDefaults():void
    { if(!in_array('sqlite',PDO::getAvailableDrivers(),true))self::markTestSkipped();$db=$this->database();$settings=new SystemSettings($db);$service=new ConfigurationService($settings);$document=$service->export();self::assertTrue($document['configuration']['notification_defaults']['in_app']['jobs']);self::assertFalse($document['configuration']['notification_defaults']['email']['jobs']);$document['configuration']['notification_defaults']['email']['jobs']=true;self::assertArrayHasKey('notification_defaults',$service->preview($document));$service->import($document);self::assertTrue((new \Modright\NotificationService($db))->preference('nonexistent-user','jobs')['email']);self::assertStringNotContainsString('nonexistent-user',json_encode($service->export(),JSON_THROW_ON_ERROR));$invalid=$service->export();$invalid['configuration']['notification_defaults']['email']['unknown']=true;$this->expectException(\InvalidArgumentException::class);$service->preview($invalid);}

    public function testConfigurationRejectsSecretFields(): void
    { if(!in_array('sqlite',PDO::getAvailableDrivers(),true))self::markTestSkipped();$db=$this->database();$document=(new ConfigurationService(new SystemSettings($db)))->export();$document['configuration']['security']['api_token']='bad';$this->expectException(\InvalidArgumentException::class);(new ConfigurationService(new SystemSettings($db)))->preview($document); }

    public function testConfigurationRejectsUnsafeRedirectProxyAndFeatureDependencies():void
    { if(!in_array('sqlite',PDO::getAvailableDrivers(),true))self::markTestSkipped();$settings=new SystemSettings($this->database());$settings->setGroup('security',['canonical_url'=>'https://packs.example.test']);$service=new ConfigurationService($settings);$redirect=$service->export();$redirect['configuration']['security']['logout_redirect']='javascript:alert(1)';try{$service->preview($redirect);self::fail('Unsafe redirect accepted.');}catch(\InvalidArgumentException){}$proxy=$service->export();$proxy['configuration']['connectivity']['proxy_enabled']=true;$proxy['configuration']['connectivity']['proxy_host']='https://attacker.example/path';try{$service->preview($proxy);self::fail('Unsafe proxy accepted.');}catch(\InvalidArgumentException){}$dependency=$service->export();$dependency['configuration']['features']['two_factor']=false;$dependency['configuration']['features']['passkeys']=true;$this->expectException(\InvalidArgumentException::class);$this->expectExceptionMessage('passkeys require two-factor');$service->preview($dependency);}

    public function testConfigurationReplaceModeDoesNotDependOnRequestGlobals():void
    { if(!in_array('sqlite',PDO::getAvailableDrivers(),true))self::markTestSkipped();$db=$this->database();$settings=new SystemSettings($db);$settings->setGroup('updates',['channel'=>'prerelease','interval_hours'=>72]);$document=(new ConfigurationService($settings))->export();$document['configuration']['updates']=['channel'=>'stable'];unset($_POST['mode']);$service=new ConfigurationService($settings);self::assertArrayHasKey('updates',$service->preview($document,'replace'));$service->import($document,'replace');self::assertSame(24,$settings->group('updates')['interval_hours']);}

    public function testConfigurationExportOmitsAndReplacePreservesDeploymentSpecificValues():void
    { if(!in_array('sqlite',PDO::getAvailableDrivers(),true))self::markTestSkipped();$db=$this->database();$settings=new SystemSettings($db);$settings->setGroup('security',['canonical_url'=>'https://private.example.test','trusted_proxies'=>['10.0.0.0/8'],'logout_redirect'=>'https://portal.example.test']);$settings->setGroup('mail',['host'=>'smtp.private.test','username'=>'private-user','from_address'=>'person@example.test']);$settings->setGroup('connectivity',['proxy_host'=>'proxy.private.test','proxy_username'=>'proxy-user']);$service=new ConfigurationService($settings);$export=$service->export();$json=json_encode($export['configuration'],JSON_THROW_ON_ERROR);foreach(['private.example.test','10.0.0.0/8','portal.example.test','smtp.private.test','private-user','person@example.test','proxy.private.test','proxy-user']as$value)self::assertStringNotContainsString($value,$json);$service->import($export,'replace');self::assertSame('https://private.example.test',$settings->group('security')['canonical_url']);self::assertSame('smtp.private.test',$settings->group('mail')['host']);self::assertSame('proxy.private.test',$settings->group('connectivity')['proxy_host']);}

    public function testRetentionRemovesOnlyExpiredAuthenticationRecords(): void
    { if(!in_array('sqlite',PDO::getAvailableDrivers(),true))self::markTestSkipped();$db=$this->database();$user=Database::id();$now=Database::now();$db->prepare('INSERT INTO users (id,username,display_name,password_hash,role,enabled,locale,tutorial_status,tutorial_step,session_version,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)')->execute([$user,'retain','Retain',password_hash('long-enough-password',PASSWORD_DEFAULT),'user',1,'en_US','completed',0,1,$now,$now]);foreach([['old','2020-01-01T00:00:00Z'],['new','2999-01-01T00:00:00Z']]as[$suffix,$expiry])$db->prepare('INSERT INTO password_reset_tokens (id,user_id,token_hash,requested_ip_hash,expires_at,created_at) VALUES (?,?,?,?,?,?)')->execute([Database::id(),$user,hash('sha256',$suffix),'ip',$expiry,$now]);$service=new RetentionService($db,new SystemSettings($db));self::assertSame(1,$service->estimate()['expired_tokens']);self::assertSame(1,$service->cleanup()['password_reset_tokens']);self::assertSame(1,(int)$db->query('SELECT COUNT(*) FROM password_reset_tokens')->fetchColumn()); }

    public function testRetentionCleanupRunsAsCancellableResumableJob():void
    { if(!in_array('sqlite',PDO::getAvailableDrivers(),true))self::markTestSkipped();$db=$this->database();$settings=new SystemSettings($db);$old=gmdate('c',time()-800*86400);$db->prepare('INSERT INTO audit_log (id,action,context,created_at) VALUES (?,?,?,?)')->execute([Database::id(),'old.event','{}',$old]);$jobs=new \Modright\JobService($db,new \Modright\PackRepository($db),new \Modright\ModrinthClient(),new \Modright\ArchiveService(),null,$settings);$id=$jobs->create('retention_cleanup',null,['estimated_records'=>1]);$first=$jobs->step($id);self::assertSame('running',$first['status']);self::assertSame(1,$first['result_data']['counts']['audit_log']);$second=$jobs->step($id);self::assertSame('completed',$second['status']); }

    public function testRetentionRemovesOnlyOldUnusedCatalogMetadata():void
    { if(!in_array('sqlite',PDO::getAvailableDrivers(),true))self::markTestSkipped();$db=$this->database();$old=gmdate('c',time()-400*86400);$db->prepare('INSERT INTO project_catalog (project_id,project_json,versions_json,game_version,loader,synced_at,last_error,updated_at) VALUES (?,?,?,?,?,?,?,?)')->execute(['unused','{}','[]','1.20.1','fabric',$old,'',$old]);$settings=new SystemSettings($db);$settings->setGroup('retention',['catalog_days'=>180]);$service=new RetentionService($db,$settings);self::assertSame(1,$service->estimate()['stale_catalog']);self::assertSame(1,$service->cleanup()['stale_catalog']);self::assertSame(0,(int)$db->query('SELECT COUNT(*) FROM project_catalog')->fetchColumn()); }

    public function testCatalogReferencedOnlyByStandardDownloadUrlIsRetained():void
    { if(!in_array('sqlite',PDO::getAvailableDrivers(),true))self::markTestSkipped();$db=$this->database();$old=gmdate('c',time()-400*86400);$db->prepare('INSERT INTO project_catalog (project_id,project_json,versions_json,game_version,loader,synced_at,last_error,updated_at) VALUES (?,?,?,?,?,?,?,?)')->execute(['used-project','{}','[]','1.20.1','fabric',$old,'',$old]);(new \Modright\PackRepository($db))->create(['formatVersion'=>1,'game'=>'minecraft','versionId'=>'1','name'=>'URL Reference','summary'=>'','files'=>[['path'=>'mods/example.jar','hashes'=>['sha1'=>str_repeat('a',40),'sha512'=>str_repeat('b',128)],'downloads'=>['https://cdn.modrinth.com/data/used-project/versions/v1/example.jar'],'fileSize'=>1]],'dependencies'=>['minecraft'=>'1.20.1','fabric-loader'=>'0.15']]);$service=new RetentionService($db,new SystemSettings($db));self::assertSame(0,$service->estimate()['stale_catalog']);self::assertSame(0,$service->cleanup()['stale_catalog']);self::assertSame(1,(int)$db->query('SELECT COUNT(*) FROM project_catalog')->fetchColumn());}

    public function testOldUnreferencedPackageFileIsReviewOnly():void
    { if(!in_array('sqlite',PDO::getAvailableDrivers(),true))self::markTestSkipped();$directory=MODRIGHT_ROOT.'/storage/packages';if(!is_dir($directory))mkdir($directory,0770,true);$path=$directory.'/orphan-review-'.bin2hex(random_bytes(6)).'.zip';file_put_contents($path,'review me');touch($path,time()-400*86400);try{$db=$this->database();$service=new RetentionService($db,new SystemSettings($db));$estimate=$service->estimate();self::assertSame(1,$estimate['review_only_orphaned_files']);self::assertSame(9,$estimate['review_only_file_bytes']);self::assertSame(0,$estimate['file_bytes']);$service->cleanup();self::assertFileExists($path);}finally{@unlink($path);}}
}
