<?php

declare(strict_types=1);

namespace Modright;

use PDO;
use ZipArchive;

final class BackupService
{
    public function __construct(private readonly PDO $db) {}

    public function export(string $destination): void
    { $partial=$destination.'.part';$complete=false;@unlink($partial);register_shutdown_function(static function()use($partial,&$complete):void{if(!$complete)@unlink($partial);});$data=['format'=>1,'created_at'=>Database::now(),'packs'=>$this->db->query('SELECT * FROM packs')->fetchAll(),'pack_options'=>$this->db->query('SELECT * FROM pack_options')->fetchAll(),'project_catalog'=>$this->db->query('SELECT * FROM project_catalog')->fetchAll(),'build_manifests'=>$this->db->query('SELECT * FROM build_manifests')->fetchAll(),'packages'=>$this->db->query('SELECT * FROM packages')->fetchAll()];$entries=[];foreach($data['packs']as$pack)$this->collectTree($entries,MODRIGHT_ROOT.'/storage/packs/'.$pack['id'],'packs/'.$pack['id'].'/');foreach($data['packages']as$package)if(is_file($package['path']))$entries[]=[(string)$package['path'],'packages/'.basename((string)$package['path'])];foreach($data['project_catalog']as$entry){$icon=MODRIGHT_ROOT.'/storage/catalog-icons/'.$entry['project_id'];if(is_file($icon))$entries[]=[$icon,'catalog-icons/'.$entry['project_id']];}try{$zip=new ZipArchive();if($zip->open($partial,ZipArchive::CREATE|ZipArchive::OVERWRITE)!==true)throw new \RuntimeException('Cannot create backup archive.');if(!$zip->addFromString('backup.json',json_encode($data,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR))||!$zip->close())throw new \RuntimeException('Cannot initialize backup archive.');foreach(array_chunk($entries,8)as$batch){@set_time_limit(30);$zip=new ZipArchive();if($zip->open($partial)!==true)throw new \RuntimeException('Cannot continue backup archive.');try{foreach($batch as[$source,$name])$this->addStoredFile($zip,$source,$name);@set_time_limit(30);if(!$zip->close())throw new \RuntimeException('Cannot finalize a backup batch.');}catch(\Throwable$e){@$zip->close();throw$e;}}if(!rename($partial,$destination))throw new \RuntimeException('Cannot publish backup archive.');$complete=true;}finally{if(!$complete)@unlink($partial);} }

    /** @return array{packs:int,catalog:int,packages:int} */
    public function restore(string $archive,bool $overwrite=false): array
    { $zip=new ZipArchive();if($zip->open($archive)!==true)throw new \InvalidArgumentException('Backup is not a valid ZIP archive.');$stage=MODRIGHT_ROOT.'/storage/temp/restore-'.Database::id();if(!mkdir($stage,0770,true)&&!is_dir($stage))throw new \RuntimeException('Cannot stage backup.');try{if($zip->numFiles>20000)throw new \InvalidArgumentException('Backup contains too many files.');$total=0;for($i=0;$i<$zip->numFiles;$i++){$stat=$zip->statIndex($i);if(!$stat)continue;$name=str_replace('\\','/',$stat['name']);ArchiveService::assertEntry($name);$total+=(int)$stat['size'];if($total>5*1024*1024*1024)throw new \InvalidArgumentException('Backup exceeds the 5 GB extraction limit.');if(str_ends_with($name,'/'))continue;$target=$stage.'/'.$name;$directory=dirname($target);if(!is_dir($directory)&&!mkdir($directory,0770,true)&&!is_dir($directory))throw new \RuntimeException('Cannot stage backup entry.');$source=$zip->getStream($stat['name']);$output=fopen($target,'wb');if(!$source||!$output)throw new \RuntimeException('Cannot extract backup entry.');stream_copy_to_stream($source,$output,(int)$stat['size']+1);fclose($source);fclose($output);}}finally{$zip->close();}$json=$stage.'/backup.json';if(!is_file($json)||filesize($json)>50*1024*1024)throw new \InvalidArgumentException('Backup metadata is missing or too large.');$data=json_decode((string)file_get_contents($json),true,512,JSON_THROW_ON_ERROR);if(($data['format']??null)!==1||!is_array($data['packs']??null))throw new \InvalidArgumentException('Unsupported backup format.');
        $this->db->beginTransaction();try{foreach($data['packs']as$row){PackRepository::validateIndex(json_decode($row['index_json'],true,512,JSON_THROW_ON_ERROR));$exists=$this->exists('packs','id',$row['id']);if($exists&&!$overwrite)throw new \RuntimeException('Pack already exists: '.$row['name'].'. Enable overwrite to replace it.');$this->replace('packs','id',$row,['id','name','slug','version_id','summary','game_version','loader','loader_version','index_json','created_at','updated_at']);}foreach($data['pack_options']??[]as$row)$this->replace('pack_options','pack_id',$row,['pack_id','options_json','updated_at']);foreach($data['project_catalog']??[]as$row)$this->replace('project_catalog','project_id',$row,['project_id','project_json','versions_json','game_version','loader','synced_at','last_error','updated_at']);foreach($data['build_manifests']??[]as$row)$this->replace('build_manifests','id',$row,['id','pack_id','version_id','manifest_json','created_at']);foreach($data['packages']??[]as$row){$basename=basename((string)$row['path']);$row['path']=MODRIGHT_ROOT.'/storage/packages/'.$basename;$this->replace('packages','id',$row,['id','pack_id','version_id','path','size','sha256','created_at']);}$this->copyTree($stage.'/packs',MODRIGHT_ROOT.'/storage/packs');$this->copyTree($stage.'/packages',MODRIGHT_ROOT.'/storage/packages');$this->copyTree($stage.'/catalog-icons',MODRIGHT_ROOT.'/storage/catalog-icons');$this->db->commit();}catch(\Throwable$e){if($this->db->inTransaction())$this->db->rollBack();throw$e;}finally{Storage::deleteTree($stage);}return['packs'=>count($data['packs']),'catalog'=>count($data['project_catalog']??[]),'packages'=>count($data['packages']??[])]; }

    /** @param list<array{string,string}> $entries */
    private function collectTree(array &$entries,string $directory,string $prefix): void
    { if(!is_dir($directory))return;$iterator=new \RecursiveIteratorIterator(new \RecursiveDirectoryIterator($directory,\FilesystemIterator::SKIP_DOTS));foreach($iterator as$file){if(!$file->isFile()||$file->isLink())continue;$relative=str_replace('\\','/',substr($file->getPathname(),strlen($directory)+1));ArchiveService::assertEntry($prefix.$relative);$entries[]=[$file->getPathname(),$prefix.$relative];} }
    private function addStoredFile(ZipArchive$zip,string$source,string$name):void
    { @set_time_limit(30);if(!$zip->addFile($source,$name))throw new \RuntimeException('Cannot add a file to the backup archive.');$zip->setCompressionName($name,ZipArchive::CM_STORE); }
    private function copyTree(string $source,string $destination): void
    { if(!is_dir($source))return;$iterator=new \RecursiveIteratorIterator(new \RecursiveDirectoryIterator($source,\FilesystemIterator::SKIP_DOTS));foreach($iterator as$file){if(!$file->isFile()||$file->isLink())continue;$relative=substr($file->getPathname(),strlen($source)+1);$target=$destination.'/'.$relative;$directory=dirname($target);if(!is_dir($directory)&&!mkdir($directory,0770,true)&&!is_dir($directory))throw new \RuntimeException('Cannot restore directory.');if(!copy($file->getPathname(),$target))throw new \RuntimeException('Cannot restore file.');} }
    private function exists(string $table,string $key,string $value): bool
    { $stmt=$this->db->prepare("SELECT COUNT(*) FROM $table WHERE $key=?");$stmt->execute([$value]);return(int)$stmt->fetchColumn()>0; }
    /** @param array<string,mixed> $row @param list<string> $columns */
    private function replace(string $table,string $key,array $row,array $columns): void
    { $values=array_map(fn($column)=>$row[$column]??null,$columns);if($this->exists($table,$key,(string)$row[$key])){$sets=implode(',',array_map(fn($column)=>"$column=?",array_values(array_filter($columns,fn($column)=>$column!==$key))));$updateValues=[];foreach($columns as$column)if($column!==$key)$updateValues[]=$row[$column]??null;$updateValues[]=$row[$key];$this->db->prepare("UPDATE $table SET $sets WHERE $key=?")->execute($updateValues);}else{$marks=implode(',',array_fill(0,count($columns),'?'));$this->db->prepare('INSERT INTO '.$table.' ('.implode(',',$columns).") VALUES ($marks)")->execute($values);} }
}
