<?php

declare(strict_types=1);

namespace Modright;

use PDO;

final class HealthService
{
    public function __construct(private readonly PDO $db,private readonly SystemSettings $settings) {}

    /** @param array<string,mixed> $server @return array<string,mixed> */
    public function report(array $server=[]): array
    {
        $checks=[];$add=static function(string$id,string$status,string$message)use(&$checks):void{$recommendation=match($status){'misconfigured'=>'Correct this configuration before relying on the affected feature.','degraded'=>'Review the related setting or recent failure and run its bounded diagnostic.','unknown'=>'Run the related bounded test or operation to establish current status.','disabled'=>'No action is required unless this feature is needed.',default=>'No action required.'};$checks[]=['id'=>$id,'status'=>$status,'message'=>$message,'recommendation'=>$recommendation];};
        $add('php',PHP_VERSION_ID>=80300?'healthy':'misconfigured','PHP '.PHP_VERSION);
        foreach(['curl','json','mbstring','openssl','pdo','zip']as$extension)$add('ext_'.$extension,extension_loaded($extension)?'healthy':'misconfigured',extension_loaded($extension)?$extension.' loaded':$extension.' missing');
        try{$this->db->query('SELECT 1')->fetchColumn();$add('database','healthy','Database connection available');}catch(\Throwable){$add('database','misconfigured','Database connection failed');}
        try{$migration=(string)$this->db->query('SELECT migration_id FROM schema_migrations ORDER BY applied_at DESC LIMIT 1')->fetchColumn();$current=hash_equals(Database::LATEST_MIGRATION,$migration);$add('migrations',$current?'healthy':'misconfigured',$current?'Latest migration applied':'Pending or unknown database migration state');}catch(\Throwable){$add('migrations','misconfigured','Migration tracking is unavailable');}
        foreach(['storage','storage/data','storage/temp','storage/packages','storage/backups']as$dir){$path=MODRIGHT_ROOT.'/'.$dir;$add('writable_'.str_replace('/','_',$dir),is_dir($path)&&is_writable($path)?'healthy':'misconfigured',$dir.(is_writable($path)?' writable':' not writable'));}
        $free=@disk_free_space(MODRIGHT_ROOT.'/storage');$add('disk',$free===false?'unknown':($free<1024*1024*1024?'degraded':'healthy'),$free===false?'Free space unavailable':self::bytes((int)$free).' free');$usage=$this->storageUsage();$add('storage_usage',$usage['truncated']?'unknown':'healthy',self::bytes($usage['bytes']).' in '.$usage['files'].' application file(s)'.($usage['truncated']?' (bounded scan; additional files exist)':''));
        $security=$this->settings->group('security');$proxies=is_array($security['trusted_proxies'])?$security['trusted_proxies']:[];$https=RequestSecurity::https($server,$proxies);$canonical=(string)$security['canonical_url'];$canonicalSecure=str_starts_with($canonical,'https://');$remoteTrusted=RequestSecurity::trusted((string)($server['REMOTE_ADDR']??''),$proxies);$forwarded=trim((string)($server['HTTP_X_FORWARDED_PROTO']??''))!=='';$add('https',$https?'healthy':'degraded',$https?'Effective request scheme is HTTPS':'Effective request scheme is HTTP');
        $add('canonical_url',$canonicalSecure?'healthy':'misconfigured',$canonical!==''?'Canonical public URL configured':'Canonical public URL missing');$proxyStatus=$forwarded?($remoteTrusted?'healthy':'misconfigured'):($proxies!==[]?'unknown':'disabled');$proxyMessage=$forwarded?($remoteTrusted?'Forwarded protocol accepted from an explicitly trusted proxy':'Forwarded protocol ignored because this request source is not trusted'):($proxies!==[]?'Trusted proxy networks are configured; this request supplied no forwarded protocol':'No trusted proxy networks configured');$add('trusted_proxy',$proxyStatus,$proxyMessage);$add('secure_cookie',$https?'healthy':'degraded',$https?'Secure session cookies active':'Secure cookie unavailable on this request');$add('security_features',$https&&$canonicalSecure?'healthy':'disabled',$https&&$canonicalSecure?'HTTPS-dependent account-security features are available':'HTTPS-dependent account-security features are unavailable');
        $mail=$this->settings->group('mail');$add('mail',(string)$mail['from_address']!==''?'healthy':'misconfigured',(string)$mail['from_address']!==''?strtoupper((string)$mail['transport']).' delivery configured':'Mail sender missing');$features=$this->settings->group('features');$lastConnectivity=$this->settings->get('system.connectivity_last');$modrinthStatus=!empty($features['modrinth'])?(is_array($lastConnectivity)?(string)($lastConnectivity['status']??'unknown'):'unknown'):'disabled';$modrinthMessage=is_array($lastConnectivity)?(string)($lastConnectivity['message']??'Connection test completed.'):'Enabled; run the bounded connection test for live status';$add('modrinth',$modrinthStatus,!empty($features['modrinth'])?$modrinthMessage:'External Modrinth access disabled');$connect=$this->settings->group('connectivity');$proxy=!empty($connect['proxy_enabled']);$proxyValid=!$proxy||(preg_match('/^[A-Za-z0-9.-]+$/',(string)$connect['proxy_host'])&&(int)$connect['proxy_port']>0);$add('modrinth_proxy',$proxy?($proxyValid?'unknown':'misconfigured'):'disabled',$proxy?'Proxy configured; use the bounded Modrinth connection test':'No Modrinth proxy');$outbound=$this->settings->group('outbound');$githubProxy=!empty($outbound['proxy_enabled']);$githubProxyValid=!$githubProxy||(preg_match('/^[A-Za-z0-9.-]+$/',(string)$outbound['proxy_host'])&&(int)$outbound['proxy_port']>0);$add('github_proxy',$githubProxy?($githubProxyValid?'unknown':'misconfigured'):'disabled',$githubProxy?'Fixed-destination GitHub proxy configured':'No general GitHub proxy');$add('updates',!empty($features['update_checks'])?'unknown':'disabled',!empty($features['update_checks'])?'GitHub update checks enabled':'Update checks disabled');
        try{$running=(int)$this->db->query("SELECT COUNT(*) FROM jobs WHERE status='running'")->fetchColumn();$stmt=$this->db->prepare("SELECT COUNT(*) FROM jobs WHERE status='running' AND updated_at<?");$stmt->execute([gmdate('c',time()-3600)]);$longRunning=(int)$stmt->fetchColumn();$stmt=$this->db->prepare("SELECT COUNT(*) FROM jobs WHERE status='failed' AND updated_at>?");$stmt->execute([gmdate('c',time()-86400)]);$failed=(int)$stmt->fetchColumn();$add('background_jobs',$failed>2||$longRunning>0?'degraded':'healthy',$running.' running ('.$longRunning.' longer than one hour), '.$failed.' failures in the last 24 hours'.($failed>2?' · repeated failures detected':''));}catch(\Throwable){$add('background_jobs','unknown','Background-job state unavailable');}
        $this->outcomeHistory($add,'cron','cron_runs','finished_at','status',['success'],['failed']);
        $this->outcomeHistory($add,'catalog_refresh','jobs','updated_at','status',['completed'],['failed','cancelled'],"type='catalog_sync'");
        $this->auditOutcomeHistory($add,'backup','backup.exported','backup.failed');
        $this->settingOutcomeHistory($add,'update_check','system.update_last_success','system.update_last_failure');
        $this->auditOutcomeHistory($add,'mail_test','mail.test_sent','mail.test_failed');
        $failed=count(array_filter($checks,fn($check)=>$check['status']==='misconfigured'));$degraded=count(array_filter($checks,fn($check)=>$check['status']==='degraded'));
        return['status'=>$failed?'misconfigured':($degraded?'degraded':'healthy'),'checks'=>$checks,'generated_at'=>Database::now(),'version'=>$this->version()];
    }

    private function version(): string{return is_file(MODRIGHT_ROOT.'/VERSION')?trim((string)file_get_contents(MODRIGHT_ROOT.'/VERSION')):'unknown';}
    /** @param list<string> $success @param list<string> $failure */
    private function outcomeHistory(callable$add,string$id,string$table,string$dateColumn,string$statusColumn,array$success,array$failure,string$where='1=1'):void
    { try{$latest=static function(PDO$db,string$table,string$dateColumn,string$statusColumn,array$states,string$where):?string{$marks=implode(',',array_fill(0,count($states),'?'));$stmt=$db->prepare("SELECT {$dateColumn} FROM {$table} WHERE {$where} AND {$statusColumn} IN ({$marks}) ORDER BY {$dateColumn} DESC LIMIT 1");$stmt->execute($states);$value=$stmt->fetchColumn();return$value===false?null:(string)$value;};$ok=$latest($this->db,$table,$dateColumn,$statusColumn,$success,$where);$failed=$latest($this->db,$table,$dateColumn,$statusColumn,$failure,$where);$status=$failed!==null&&($ok===null||strcmp($failed,$ok)>0)?'degraded':($ok!==null?'healthy':'unknown');$add($id,$status,'Last success: '.($ok??'Never').' · Last failure: '.($failed??'Never'));}catch(\Throwable){$add($id,'unknown','History unavailable');}}
    private function auditOutcomeHistory(callable$add,string$id,string$successAction,string$failureAction):void
    { try{$latest=function(string$action):?string{$stmt=$this->db->prepare('SELECT created_at FROM audit_log WHERE action=? ORDER BY created_at DESC LIMIT 1');$stmt->execute([$action]);$value=$stmt->fetchColumn();return$value===false?null:(string)$value;};$ok=$latest($successAction);$failed=$latest($failureAction);$status=$failed!==null&&($ok===null||strcmp($failed,$ok)>0)?'degraded':($ok!==null?'healthy':'unknown');$add($id,$status,'Last success: '.($ok??'Never').' · Last failure: '.($failed??'Never'));}catch(\Throwable){$add($id,'unknown','History unavailable');}}
    private function settingOutcomeHistory(callable$add,string$id,string$successKey,string$failureKey):void
    { $ok=$this->settings->get($successKey);$failed=$this->settings->get($failureKey);$ok=is_string($ok)&&$ok!==''?$ok:null;$failed=is_string($failed)&&$failed!==''?$failed:null;$status=$failed!==null&&($ok===null||strcmp($failed,$ok)>0)?'degraded':($ok!==null?'healthy':'unknown');$add($id,$status,'Last success: '.($ok??'Never').' · Last failure: '.($failed??'Never')); }
    /** @return array{bytes:int,files:int,truncated:bool} */
    private function storageUsage():array
    { $bytes=0;$files=0;$root=MODRIGHT_ROOT.'/storage';if(!is_dir($root))return compact('bytes','files')+['truncated'=>false];try{$iterator=new \RecursiveIteratorIterator(new \RecursiveDirectoryIterator($root,\FilesystemIterator::SKIP_DOTS));foreach($iterator as$file){if(!$file->isFile()||$file->isLink())continue;$bytes+=$file->getSize();$files++;if($files>=10000)return compact('bytes','files')+['truncated'=>true];}}catch(\Throwable){return compact('bytes','files')+['truncated'=>true];}return compact('bytes','files')+['truncated'=>false];}
    private static function bytes(int $bytes): string{foreach(['B','KiB','MiB','GiB','TiB']as$unit){if($bytes<1024||$unit==='TiB')return number_format($bytes,1).' '.$unit;$bytes=(int)($bytes/1024);}return'unknown';}
}
