<?php
declare(strict_types=1);
namespace Modright;
use PDO;

final class UserService
{
    public function __construct(private readonly PDO $db) {}
    /** @return array<string,mixed>|null */
    public function authenticate(string $username,string $password): ?array
    { $stmt=$this->db->prepare('SELECT * FROM users WHERE username=?');$stmt->execute([trim($username)]);$user=$stmt->fetch();if(!$user||(int)$user['enabled']!==1||!password_verify($password,$user['password_hash']))return null;$now=Database::now();$this->db->prepare('UPDATE users SET last_login_at=?,updated_at=? WHERE id=?')->execute([$now,$now,$user['id']]);$user['last_login_at']=$now;return$user; }
    /** @return array<string,mixed> */
    public function find(string $id): array
    { $stmt=$this->db->prepare('SELECT * FROM users WHERE id=?');$stmt->execute([$id]);$user=$stmt->fetch();if(!$user)throw new HttpException(404,'User not found.');return$user; }
    /** @return list<array<string,mixed>> */ public function all(): array { return$this->db->query('SELECT * FROM users ORDER BY username')->fetchAll(); }
    public function create(string $username,string $displayName,string $password,string $role,string $locale,?string $email=null): string
    { if(!preg_match('/^[A-Za-z0-9_.-]{3,50}$/',$username)||strlen($password)<12||!in_array($role,['admin','user'],true))throw new \InvalidArgumentException('Enter a valid username, role, and password of at least 12 characters.');if($email===null||trim($email)==='')throw new \InvalidArgumentException('Email is required.');$email=self::normalizeEmail($email);$id=Database::id();$now=Database::now();$stmt=$this->db->prepare('INSERT INTO users (id,username,display_name,email,password_hash,role,enabled,locale,tutorial_status,tutorial_step,session_version,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)');try{$stmt->execute([$id,$username,$displayName?:$username,$email,password_hash($password,PASSWORD_DEFAULT),$role,1,Translator::normalize($locale),'not_started',0,1,$now,$now]);}catch(\PDOException$e){throw new \InvalidArgumentException('Username or email is already in use.',0,$e);}$this->audit('user.created',['user_id'=>$id,'role'=>$role]);return$id; }
    public function update(string $id,string $displayName,string $role,bool $enabled,string $locale,?string $password=null): void
    { $user=$this->find($id);if(!in_array($role,['admin','user'],true))throw new \InvalidArgumentException('Invalid role.');if($user['role']==='admin'&&(int)$user['enabled']===1&&($role!=='admin'||!$enabled)){if((int)$this->db->query("SELECT COUNT(*) FROM users WHERE role='admin' AND enabled=1")->fetchColumn()<=1)throw new \InvalidArgumentException('At least one enabled administrator is required.');}$hash=$user['password_hash'];if($password!==null&&$password!==''){if(strlen($password)<12)throw new \InvalidArgumentException('New password must contain at least 12 characters.');$hash=password_hash($password,PASSWORD_DEFAULT);}$sessionVersion=(int)$user['session_version']+((int)$user['enabled']!==(int)$enabled||$user['role']!==$role||$hash!==$user['password_hash']?1:0);$stmt=$this->db->prepare('UPDATE users SET display_name=?,role=?,enabled=?,locale=?,password_hash=?,session_version=?,updated_at=? WHERE id=?');$stmt->execute([$displayName,$role,$enabled?1:0,Translator::normalize($locale),$hash,$sessionVersion,Database::now(),$id]);$this->audit('user.updated',['user_id'=>$id,'role'=>$role,'enabled'=>$enabled]); }
    public function preferences(string $id,string $displayName,string $locale): void
    { $stmt=$this->db->prepare('UPDATE users SET display_name=?,locale=?,updated_at=? WHERE id=?');$stmt->execute([$displayName,Translator::normalize($locale),Database::now(),$id]); }
    public function tutorial(string $id,string $status,int $step): void
    { if(!in_array($status,['not_started','in_progress','skipped','completed'],true))throw new \InvalidArgumentException('Invalid tutorial state.');$stmt=$this->db->prepare('UPDATE users SET tutorial_status=?,tutorial_step=?,updated_at=? WHERE id=?');$stmt->execute([$status,max(0,min(20,$step)),Database::now(),$id]); }
    public function setEmail(string $id,string $email,bool $verified=false): void
    { $email=self::normalizeEmail($email);try{$this->db->prepare('UPDATE users SET email=?,email_verified_at=?,updated_at=?,session_version=session_version+1 WHERE id=?')->execute([$email,$verified?Database::now():null,Database::now(),$id]);}catch(\PDOException$e){throw new \InvalidArgumentException('Email is already in use.',0,$e);}$this->db->prepare('UPDATE user_sessions SET revoked_at=? WHERE user_id=? AND revoked_at IS NULL')->execute([Database::now(),$id]);$this->audit('user.email_changed',['user_id'=>$id]);$this->notifySecurityChange($id,'Email address changed','Your Cogwork Engine account email address was changed. Verify the new address and review active sessions if this was unexpected.'); }
    /** @return array<string,mixed>|null */
    public function findByEmail(string $email): ?array
    { try{$email=self::normalizeEmail($email);}catch(\InvalidArgumentException){return null;}$stmt=$this->db->prepare('SELECT * FROM users WHERE email=? AND enabled=1 AND email_verified_at IS NOT NULL');$stmt->execute([$email]);$user=$stmt->fetch();return$user?:null; }
    public function setPassword(string $id,string $password): void
    { if(strlen($password)<12)throw new \InvalidArgumentException('Password must contain at least 12 characters.');$this->db->prepare('UPDATE users SET password_hash=?,session_version=session_version+1,updated_at=? WHERE id=?')->execute([password_hash($password,PASSWORD_DEFAULT),Database::now(),$id]);$this->db->prepare('UPDATE user_sessions SET revoked_at=? WHERE user_id=? AND revoked_at IS NULL')->execute([Database::now(),$id]);$this->audit('user.password_changed',['user_id'=>$id]);$this->notifySecurityChange($id,'Password changed','Your Cogwork Engine account password was changed. Review active sessions and authentication factors if this was unexpected.'); }
    public static function normalizeEmail(string $email): string
    { $email=mb_strtolower(trim($email));if(strlen($email)>254||filter_var($email,FILTER_VALIDATE_EMAIL)===false)throw new \InvalidArgumentException('Enter a valid email address.');return$email; }
    private function audit(string $action,array $context): void { $context['actor_user_id']=$_SESSION['user_id']??$_SESSION['admin_id']??null;$stmt=$this->db->prepare('INSERT INTO audit_log (id,action,context,created_at) VALUES (?,?,?,?)');$stmt->execute([Database::id(),$action,json_encode($context,JSON_THROW_ON_ERROR),Database::now()]); }
    private function notifySecurityChange(string$userId,string$title,string$message):void
    { try{(new NotificationService($this->db))->send($userId,'security','critical',$title,$message,Application::url('account').'#security',false);if(!Config::installed())return;$settings=new SystemSettings($this->db);$mail=$settings->group('mail');$maintenance=(new MaintenanceService($settings))->state();$mail['paused']=!empty($maintenance['active'])&&!empty($maintenance['pause_mail']);if((string)$mail['from_address']==='')return;$mail['password']=(new SecretStore())->get('smtp.password');$email=$this->find($userId)['email'];if(is_string($email)&&$email!=='')(new MailService($mail))->send($email,$title,$message."\n\nNo password, token, or authentication secret is included in this message.");}catch(\Throwable){/* Account mutation must not be rolled back because optional notification delivery failed. */} }
}
