const { test, expect } = require('@playwright/test');
const fs = require('fs');

test('install, sign in, navigate account/admin/help, and sign out', async ({ page }) => {
  test.setTimeout(60000);
  await page.goto('/index.php');
  await expect(page.getByRole('heading', { name: 'Install Cogwork Engine' })).toBeVisible();
  await expect(page.getByText('HTTPS was not detected')).toBeVisible();
  await page.getByLabel('Administrator username').fill('browseradmin');
  await page.getByLabel('Administrator email').fill('browseradmin@example.test');
  await page.getByLabel('Administrator password', { exact: true }).fill('browser-test-password');
  await page.getByLabel('Repeat administrator password').fill('different-browser-password');
  await page.getByRole('button', { name: 'Install' }).click();
  await expect(page.getByText('The administrator passwords do not match.')).toBeVisible();
  await page.getByLabel('Administrator username').fill('browseradmin');
  await page.getByLabel('Administrator email').fill('browseradmin@example.test');
  await page.getByLabel('Administrator password', { exact: true }).fill('browser-test-password');
  await page.getByLabel('Repeat administrator password').fill('browser-test-password');
  await page.getByRole('button', { name: 'Install' }).click();
  await expect(page.getByRole('heading', { name: 'Sign in' })).toBeVisible();

  await page.getByLabel('Username').fill('browseradmin');
  await page.getByLabel('Password').fill('browser-test-password');
  await page.getByRole('button', { name: 'Sign in' }).click();
  await expect(page.getByRole('heading', { name: 'Modpacks' })).toBeVisible();
  await expect(page.getByText('Trusted HTTPS is not active')).toHaveCount(0);
  await expect(page.getByRole('dialog').getByRole('heading', { name: 'Your account menu' })).toBeVisible();
  await expect(page.locator('[data-account-menu] summary')).toHaveClass(/tour-target/);
  await page.locator('[data-account-menu] summary').click();
  await expect(page.getByRole('menuitem', { name: 'Account', exact: true })).toBeVisible();
  await page.getByRole('dialog').getByRole('button', { name: 'Next' }).click();
  await expect(page.getByRole('dialog').getByRole('heading', { name: 'Create a modpack' })).toBeVisible();
  await page.locator('a.tour-target').click();
  await expect(page.getByRole('heading', { name: 'Create modpack' })).toBeVisible();
  await expect(page.getByRole('dialog').getByRole('heading', { name: 'Compatible versions' })).toBeVisible();
  await expect(page.locator('[data-minecraft-version]')).toHaveClass(/tour-target/);
  await page.getByRole('dialog').getByRole('button', { name: 'Skip tutorial' }).click();
  await expect(page.getByRole('heading', { name: 'Modpacks' })).toBeVisible();

  // Keep browser tests deterministic and independent from live catalog services.
  fs.writeFileSync('/e2e-storage/catalog-minecraft.json', JSON.stringify(['1.20.1']));
  fs.writeFileSync('/e2e-storage/catalog-loader-v3-fabric-1.20.1.json', JSON.stringify(['0.15.11']));
  await page.getByRole('link', { name: 'New pack' }).click();
  await page.getByLabel('Name').fill('Browser Test Pack');
  await page.getByLabel('Minecraft version').selectOption('1.20.1');
  await expect(page.getByLabel('Loader version')).toBeEnabled();
  await page.getByLabel('Loader version').selectOption('0.15.11');
  await page.getByRole('button', { name: 'Create pack' }).click();
  await expect(page.getByRole('heading', { name: 'Browser Test Pack' })).toBeVisible();
  await page.getByRole('link', { name: 'Cogwork Engine' }).click();

  await page.locator('[data-account-menu] summary').click();
  await expect(page.getByRole('menuitem', { name: 'Account', exact: true })).toBeVisible();
  await expect(page.getByRole('menuitem', { name: 'Administration' })).toBeVisible();
  await expect(page.getByRole('menuitem', { name: 'Change password' })).toBeVisible();
  await expect(page.getByLabel('Language')).toBeVisible();
  await page.locator('[data-account-menu]').press('ArrowDown');
  await expect(page.getByRole('menuitem', { name: 'Account', exact: true })).toBeFocused();
  await page.locator('[data-account-menu]').press('Escape');
  await expect(page.locator('[data-account-menu]')).not.toHaveAttribute('open', '');
  await expect(page.locator('[data-account-menu] summary')).toBeFocused();
  await page.locator('[data-account-menu] summary').click();
  await page.locator('main').click({ position: { x: 2, y: 2 } });
  await expect(page.locator('[data-account-menu]')).not.toHaveAttribute('open', '');
  await page.setViewportSize({ width: 390, height: 844 });
  await page.locator('[data-account-menu] summary').click();
  const menuBox = await page.locator('.account-menu-panel').boundingBox();
  expect(menuBox.x).toBeGreaterThanOrEqual(0);
  expect(menuBox.x + menuBox.width).toBeLessThanOrEqual(390);
  await page.emulateMedia({ reducedMotion: 'reduce' });
  expect(await page.locator('.account-menu-panel').evaluate(node => getComputedStyle(node).transitionDuration)).toBe('0s');
  await page.emulateMedia({ reducedMotion: 'no-preference' });
  await page.setViewportSize({ width: 1280, height: 720 });
  await page.getByRole('menuitem', { name: 'Administration' }).click();
  await expect(page.getByRole('heading', { name: 'Administration' })).toBeVisible();
  const packActions = page.locator('.table-actions').first();
  await packActions.locator('summary').click();
  await expect(packActions.getByRole('link', { name: 'Open' })).toBeVisible();
  expect(await page.locator('.admin-pack-table').evaluate(node => node.scrollWidth <= node.clientWidth)).toBe(true);
  await page.getByRole('link', { name: 'System', exact: true }).click();
  await expect(page.getByText(/Overall status:/)).toBeVisible();
  await expect(page.getByText(`Cogwork Engine ${fs.readFileSync('/work/VERSION', 'utf8').trim()}`)).toBeVisible();
  await expect(page.locator('.system-health')).toBeVisible();
  await expect(page.locator('.system-settings')).toBeHidden();
  await expect(page.locator('.system-nav-card')).toHaveCount(7);
  await expect(page.getByText('Trusted HTTPS is not active')).toBeVisible();
  await page.getByRole('link', { name: /^Security/ }).click();
  await expect(page.locator('.system-health')).toBeHidden();
  const securityPanel = page.locator('.system-settings > details', { hasText: 'Security and public URL' });
  await securityPanel.locator('summary').click();
  await securityPanel.getByLabel('Post-logout redirect').fill('/index.php?route=login&logged_out=1');
  await securityPanel.getByRole('button', { name: 'Save security settings' }).click();
  await expect(page.getByRole('heading', { name: 'Administration' })).toBeVisible();
  await expect(page.locator('[onclick]')).toHaveCount(0);
  expect((await page.request.get('/index.php?route=admin&tab=system')).headers()['content-security-policy']).toContain("script-src-attr 'none'");
  await expect(page.locator('.system-settings > details', { hasText: 'Retention policy' })).toHaveCount(1);
  await expect(page.locator('.system-settings > details', { hasText: 'Maintenance processing policy' })).toHaveCount(1);
  await expect(page.locator('.system-settings > details', { hasText: 'Feature reference and diagnostics' })).toHaveCount(1);
  await expect(page.locator('.system-settings > details', { hasText: 'General outbound proxy' })).toHaveCount(1);
  await expect(page.locator('.system-settings > details', { hasText: 'Password recovery policy' })).toHaveCount(1);
  await expect(page.locator('.system-settings > details', { hasText: 'Backups, restore, migration mappings, and cron' })).toHaveCount(1);
  await expect(page.locator('main > details.card')).toHaveCount(0);
  await page.getByRole('link', { name: /^Features/ }).click();
  const features = page.locator('.system-settings > details', { has: page.getByText('Features', { exact: true }) });
  await features.locator('summary').click();
  await expect(features.locator('.feature-group')).toHaveCount(3);
  await features.getByLabel('Search feature controls').fill('Windows Hello');
  await expect(features.locator('.feature-control', { hasText: 'Passkeys / Windows Hello' })).toBeVisible();
  await expect(features.locator('.feature-control', { hasText: 'Modrinth connectivity' })).toBeHidden();
  await features.getByLabel('Search feature controls').fill('Modrinth');
  await features.getByLabel('Modrinth connectivity').uncheck();
  await features.getByRole('button', { name: 'Save features' }).click();
  await page.getByRole('link', { name: 'Cogwork Engine' }).click();
  await page.getByRole('link', { name: 'Browser Test Pack' }).click();
  await expect(page.getByText('Live Modrinth actions are hidden.')).toBeVisible();
  await expect(page.getByRole('link', { name: 'Add mod' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Migration planner' })).toHaveCount(0);
  await expect(page.getByRole('button', { name: 'Refresh catalog' })).toHaveCount(0);
  await page.getByRole('link', { name: 'Add mod' }).click();
  await expect(page.getByText('Search uses saved catalog metadata only.')).toBeVisible();
  await expect(page.getByText('Upload local/private JAR')).toBeVisible();
  await expect(page.getByText('Add exact Modrinth version ID')).toHaveCount(0);
  await page.locator('[data-account-menu] summary').click();
  await page.getByRole('menuitem', { name: 'Administration' }).click();
  await page.getByRole('link', { name: 'System', exact: true }).click();
  await page.getByRole('link', { name: /^Features/ }).click();
  const restoreFeatures = page.locator('.system-settings > details', { has: page.getByText('Features', { exact: true }) });
  await restoreFeatures.locator('summary').click();
  await restoreFeatures.getByLabel('Search feature controls').fill('Modrinth');
  await restoreFeatures.getByLabel('Modrinth connectivity').check();
  await restoreFeatures.getByRole('button', { name: 'Save features' }).click();

  // Create a least-privilege account and explicitly assign Viewer access.
  await page.getByRole('link', { name: 'Users', exact: true }).click();
  await page.getByRole('link', { name: 'New user' }).click();
  await page.getByLabel('Username').fill('browserviewer');
  await page.getByLabel('Display name').fill('Browser Viewer');
  await page.getByLabel('Email').fill('browserviewer@example.test');
  await page.getByLabel('Password').fill('browser-viewer-password');
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('link', { name: 'Browser Viewer' }).click();
  await page.getByLabel('Pack').selectOption({ label: 'Browser Test Pack' });
  await page.getByLabel('Permission preset').selectOption('viewer');
  await page.getByRole('button', { name: 'Save assignment' }).click();
  await expect(page.getByRole('heading', { name: 'Explicit pack assignments' })).toBeVisible();

  await page.goto('/index.php?route=admin&tab=system&view=maintenance');

  await page.getByRole('link', { name: 'Manage announcements' }).click();
  await page.getByRole('link', { name: 'New announcement' }).click();
  await page.getByLabel('English title').fill('Browser announcement');
  await page.getByLabel('German title').fill('Browser-Ankündigung');
  await page.getByLabel('English message').fill('This verifies announcement delivery.');
  await page.getByLabel('German message').fill('Dies prüft die Auslieferung von Ankündigungen.');
  await page.getByRole('button', { name: 'Create announcement' }).click();
  await expect(page.getByRole('cell', { name: 'Browser announcement' })).toBeVisible();
  await page.getByRole('link', { name: 'Cogwork Engine' }).click();
  await expect(page.getByRole('status', { name: 'Information announcement' }).getByText('Browser announcement')).toBeVisible();
  await page.locator('.notification-link').click();
  await expect(page.getByRole('heading', { name: 'Notifications' })).toBeVisible();
  let announcementNotice = page.locator('article.notification', { hasText: 'Browser announcement' });
  await expect(announcementNotice.getByText('Unread', { exact: true })).toBeVisible();
  await announcementNotice.getByRole('button', { name: 'Acknowledge' }).click();
  announcementNotice = page.locator('article.notification', { hasText: 'Browser announcement' });
  await expect(announcementNotice.getByText('Acknowledged', { exact: true })).toBeVisible();
  await announcementNotice.getByRole('button', { name: 'Archive' }).click();
  await page.getByRole('link', { name: 'Archived notifications' }).click();
  announcementNotice = page.locator('article.notification', { hasText: 'Browser announcement' });
  await expect(announcementNotice.getByText('Archived', { exact: true })).toBeVisible();

  await page.getByRole('link', { name: 'Help' }).click();
  await expect(page.getByRole('heading', { name: 'Help center' })).toBeVisible();
  await expect(page.getByText(`Documentation for Cogwork Engine ${fs.readFileSync('/work/VERSION', 'utf8').trim()}`)).toBeVisible();
  await page.locator('[data-account-menu] summary').click();
  await page.getByRole('menuitem', { name: 'Sign out' }).click();
  await expect(page.getByRole('heading', { name: 'Sign in' })).toBeVisible();

  await page.getByLabel('Username').fill('browserviewer');
  await page.getByLabel('Password').fill('browser-viewer-password');
  await page.getByRole('button', { name: 'Sign in' }).click();
  await page.getByRole('dialog').getByRole('button', { name: 'Skip tutorial' }).click();
  await page.getByRole('link', { name: 'Browser Test Pack' }).click();
  await expect(page.getByRole('heading', { name: 'Browser Test Pack' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Settings' })).toHaveCount(0);
  await expect(page.getByRole('link', { name: 'Add mod' })).toHaveCount(0);
  await expect(page.getByRole('link', { name: 'Build' })).toHaveCount(0);
  await expect(page.getByRole('link', { name: 'Share' })).toHaveCount(0);
  await expect(page.getByRole('heading', { name: 'Danger zone' })).toHaveCount(0);
  await expect(page.getByRole('link', { name: 'Edit' })).toHaveCount(0);
  await expect(page.getByRole('menuitem', { name: 'Administration' })).toHaveCount(0);
  const forbidden = await page.request.get('/index.php?route=admin');
  expect(forbidden.status()).toBe(403);

  // Maintenance must preserve administrator recovery while returning 503 to users.
  await page.locator('[data-account-menu] summary').click();
  await page.getByRole('menuitem', { name: 'Sign out' }).click();
  await page.getByLabel('Username').fill('browseradmin');
  await page.getByLabel('Password').fill('browser-test-password');
  await page.getByRole('button', { name: 'Sign in' }).click();
  await page.goto('/index.php?route=admin&tab=system&view=maintenance');
  await expect(page.getByRole('status', { name: 'Information announcement' }).getByText('Browser announcement')).toBeVisible();
  const maintenance = page.locator('.system-settings > details', { hasText: 'Maintenance mode' });
  await maintenance.locator('summary').click();
  await maintenance.getByLabel('Enable maintenance').check();
  await maintenance.getByLabel('English message').fill('Browser maintenance window');
  await maintenance.getByLabel('Ends at (UTC)').fill(new Date(Date.now() + 60 * 60 * 1000).toISOString().slice(0, 16));
  await maintenance.getByRole('button', { name: 'Save maintenance' }).click();
  await expect(page.getByText('Maintenance mode is active')).toBeVisible();
  await page.locator('[data-account-menu] summary').click();
  await page.getByRole('menuitem', { name: 'Sign out' }).click();
  await page.getByLabel('Username').fill('browserviewer');
  await page.getByLabel('Password').fill('browser-viewer-password');
  const [maintenanceResponse] = await Promise.all([
    page.waitForResponse(response => response.url().includes('/index.php') && response.status() === 503),
    page.getByRole('button', { name: 'Sign in' }).click(),
  ]);
  expect(maintenanceResponse.status()).toBe(503);
  expect(Number(maintenanceResponse.headers()['retry-after'])).toBeGreaterThan(0);
  await expect(page.getByRole('heading', { name: 'Maintenance' })).toBeVisible();
  await expect(page.getByText('Browser maintenance window')).toBeVisible();
  await expect(page.getByText(/Estimated return:/)).toBeVisible();

  await page.context().clearCookies();
  await page.goto('/index.php?route=login');
  await page.getByLabel('Username').fill('browseradmin');
  await page.getByLabel('Password').fill('browser-test-password');
  await page.getByRole('button', { name: 'Sign in' }).click();
  await page.goto('/index.php?route=admin&tab=system&view=maintenance');
  await maintenance.locator('summary').click();
  await maintenance.getByLabel('Enable maintenance').uncheck();
  await maintenance.getByRole('button', { name: 'Save maintenance' }).click();
  await expect(page.getByText('Maintenance mode is active')).toHaveCount(0);
});
